/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef NfsRpc_H
#define NfsRpc_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include "NfsRpc_types.h"



#ifdef _WIN32
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class NfsRpcIf {
 public:
  virtual ~NfsRpcIf() {}
  virtual int32_t xmp_create(const std::string& tpath, const int32_t mode, const thrift_fuse_file_info& tfi) = 0;
  virtual int32_t xmp_unlink(const std::string& tpath) = 0;
  virtual void xmp_getattr(thrift_getattr_reply& _return, const std::string& tpath, const thrift_stat& stbuf) = 0;
  virtual int32_t xmp_setattr(const std::string& tpath, const thrift_stat& stbuf) = 0;
  virtual void xmp_read(thrift_read_reply& _return, const std::string& tpath, const std::string& tbuf, const int64_t size, const int64_t offset, const thrift_fuse_file_info& tfi) = 0;
  virtual int32_t xmp_write(const std::string& tpath, const std::string& tbuf, const int64_t size, const int64_t offset, const thrift_fuse_file_info& tfi) = 0;
  virtual int32_t xmp_rename(const std::string& tfrom, const std::string& tto) = 0;
  virtual int32_t xmp_mkdir(const std::string& tpath, const int32_t mode) = 0;
  virtual int32_t xmp_rmdir(const std::string& tpath) = 0;
  virtual void xmp_statfs(thrift_statfs_reply& _return, const std::string& tpath, const thrift_statvfs& tstbuf) = 0;
  virtual void xmp_open(thrift_open_reply& _return, const std::string& tpath, const thrift_fuse_file_info& tfi) = 0;
  virtual int32_t xmp_access(const std::string& tpath, const int32_t mask) = 0;
  virtual int32_t xmp_mknod(const std::string& tpath, const int32_t mode, const int64_t rdev) = 0;
};

class NfsRpcIfFactory {
 public:
  typedef NfsRpcIf Handler;

  virtual ~NfsRpcIfFactory() {}

  virtual NfsRpcIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(NfsRpcIf* /* handler */) = 0;
};

class NfsRpcIfSingletonFactory : virtual public NfsRpcIfFactory {
 public:
  NfsRpcIfSingletonFactory(const boost::shared_ptr<NfsRpcIf>& iface) : iface_(iface) {}
  virtual ~NfsRpcIfSingletonFactory() {}

  virtual NfsRpcIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(NfsRpcIf* /* handler */) {}

 protected:
  boost::shared_ptr<NfsRpcIf> iface_;
};

class NfsRpcNull : virtual public NfsRpcIf {
 public:
  virtual ~NfsRpcNull() {}
  int32_t xmp_create(const std::string& /* tpath */, const int32_t /* mode */, const thrift_fuse_file_info& /* tfi */) {
    int32_t _return = 0;
    return _return;
  }
  int32_t xmp_unlink(const std::string& /* tpath */) {
    int32_t _return = 0;
    return _return;
  }
  void xmp_getattr(thrift_getattr_reply& /* _return */, const std::string& /* tpath */, const thrift_stat& /* stbuf */) {
    return;
  }
  int32_t xmp_setattr(const std::string& /* tpath */, const thrift_stat& /* stbuf */) {
    int32_t _return = 0;
    return _return;
  }
  void xmp_read(thrift_read_reply& /* _return */, const std::string& /* tpath */, const std::string& /* tbuf */, const int64_t /* size */, const int64_t /* offset */, const thrift_fuse_file_info& /* tfi */) {
    return;
  }
  int32_t xmp_write(const std::string& /* tpath */, const std::string& /* tbuf */, const int64_t /* size */, const int64_t /* offset */, const thrift_fuse_file_info& /* tfi */) {
    int32_t _return = 0;
    return _return;
  }
  int32_t xmp_rename(const std::string& /* tfrom */, const std::string& /* tto */) {
    int32_t _return = 0;
    return _return;
  }
  int32_t xmp_mkdir(const std::string& /* tpath */, const int32_t /* mode */) {
    int32_t _return = 0;
    return _return;
  }
  int32_t xmp_rmdir(const std::string& /* tpath */) {
    int32_t _return = 0;
    return _return;
  }
  void xmp_statfs(thrift_statfs_reply& /* _return */, const std::string& /* tpath */, const thrift_statvfs& /* tstbuf */) {
    return;
  }
  void xmp_open(thrift_open_reply& /* _return */, const std::string& /* tpath */, const thrift_fuse_file_info& /* tfi */) {
    return;
  }
  int32_t xmp_access(const std::string& /* tpath */, const int32_t /* mask */) {
    int32_t _return = 0;
    return _return;
  }
  int32_t xmp_mknod(const std::string& /* tpath */, const int32_t /* mode */, const int64_t /* rdev */) {
    int32_t _return = 0;
    return _return;
  }
};

typedef struct _NfsRpc_xmp_create_args__isset {
  _NfsRpc_xmp_create_args__isset() : tpath(false), mode(false), tfi(false) {}
  bool tpath :1;
  bool mode :1;
  bool tfi :1;
} _NfsRpc_xmp_create_args__isset;

class NfsRpc_xmp_create_args {
 public:

  NfsRpc_xmp_create_args(const NfsRpc_xmp_create_args&);
  NfsRpc_xmp_create_args& operator=(const NfsRpc_xmp_create_args&);
  NfsRpc_xmp_create_args() : tpath(), mode(0) {
  }

  virtual ~NfsRpc_xmp_create_args() throw();
  std::string tpath;
  int32_t mode;
  thrift_fuse_file_info tfi;

  _NfsRpc_xmp_create_args__isset __isset;

  void __set_tpath(const std::string& val);

  void __set_mode(const int32_t val);

  void __set_tfi(const thrift_fuse_file_info& val);

  bool operator == (const NfsRpc_xmp_create_args & rhs) const
  {
    if (!(tpath == rhs.tpath))
      return false;
    if (!(mode == rhs.mode))
      return false;
    if (!(tfi == rhs.tfi))
      return false;
    return true;
  }
  bool operator != (const NfsRpc_xmp_create_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const NfsRpc_xmp_create_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class NfsRpc_xmp_create_pargs {
 public:


  virtual ~NfsRpc_xmp_create_pargs() throw();
  const std::string* tpath;
  const int32_t* mode;
  const thrift_fuse_file_info* tfi;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _NfsRpc_xmp_create_result__isset {
  _NfsRpc_xmp_create_result__isset() : success(false) {}
  bool success :1;
} _NfsRpc_xmp_create_result__isset;

class NfsRpc_xmp_create_result {
 public:

  NfsRpc_xmp_create_result(const NfsRpc_xmp_create_result&);
  NfsRpc_xmp_create_result& operator=(const NfsRpc_xmp_create_result&);
  NfsRpc_xmp_create_result() : success(0) {
  }

  virtual ~NfsRpc_xmp_create_result() throw();
  int32_t success;

  _NfsRpc_xmp_create_result__isset __isset;

  void __set_success(const int32_t val);

  bool operator == (const NfsRpc_xmp_create_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const NfsRpc_xmp_create_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const NfsRpc_xmp_create_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _NfsRpc_xmp_create_presult__isset {
  _NfsRpc_xmp_create_presult__isset() : success(false) {}
  bool success :1;
} _NfsRpc_xmp_create_presult__isset;

class NfsRpc_xmp_create_presult {
 public:


  virtual ~NfsRpc_xmp_create_presult() throw();
  int32_t* success;

  _NfsRpc_xmp_create_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _NfsRpc_xmp_unlink_args__isset {
  _NfsRpc_xmp_unlink_args__isset() : tpath(false) {}
  bool tpath :1;
} _NfsRpc_xmp_unlink_args__isset;

class NfsRpc_xmp_unlink_args {
 public:

  NfsRpc_xmp_unlink_args(const NfsRpc_xmp_unlink_args&);
  NfsRpc_xmp_unlink_args& operator=(const NfsRpc_xmp_unlink_args&);
  NfsRpc_xmp_unlink_args() : tpath() {
  }

  virtual ~NfsRpc_xmp_unlink_args() throw();
  std::string tpath;

  _NfsRpc_xmp_unlink_args__isset __isset;

  void __set_tpath(const std::string& val);

  bool operator == (const NfsRpc_xmp_unlink_args & rhs) const
  {
    if (!(tpath == rhs.tpath))
      return false;
    return true;
  }
  bool operator != (const NfsRpc_xmp_unlink_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const NfsRpc_xmp_unlink_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class NfsRpc_xmp_unlink_pargs {
 public:


  virtual ~NfsRpc_xmp_unlink_pargs() throw();
  const std::string* tpath;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _NfsRpc_xmp_unlink_result__isset {
  _NfsRpc_xmp_unlink_result__isset() : success(false) {}
  bool success :1;
} _NfsRpc_xmp_unlink_result__isset;

class NfsRpc_xmp_unlink_result {
 public:

  NfsRpc_xmp_unlink_result(const NfsRpc_xmp_unlink_result&);
  NfsRpc_xmp_unlink_result& operator=(const NfsRpc_xmp_unlink_result&);
  NfsRpc_xmp_unlink_result() : success(0) {
  }

  virtual ~NfsRpc_xmp_unlink_result() throw();
  int32_t success;

  _NfsRpc_xmp_unlink_result__isset __isset;

  void __set_success(const int32_t val);

  bool operator == (const NfsRpc_xmp_unlink_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const NfsRpc_xmp_unlink_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const NfsRpc_xmp_unlink_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _NfsRpc_xmp_unlink_presult__isset {
  _NfsRpc_xmp_unlink_presult__isset() : success(false) {}
  bool success :1;
} _NfsRpc_xmp_unlink_presult__isset;

class NfsRpc_xmp_unlink_presult {
 public:


  virtual ~NfsRpc_xmp_unlink_presult() throw();
  int32_t* success;

  _NfsRpc_xmp_unlink_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _NfsRpc_xmp_getattr_args__isset {
  _NfsRpc_xmp_getattr_args__isset() : tpath(false), stbuf(false) {}
  bool tpath :1;
  bool stbuf :1;
} _NfsRpc_xmp_getattr_args__isset;

class NfsRpc_xmp_getattr_args {
 public:

  NfsRpc_xmp_getattr_args(const NfsRpc_xmp_getattr_args&);
  NfsRpc_xmp_getattr_args& operator=(const NfsRpc_xmp_getattr_args&);
  NfsRpc_xmp_getattr_args() : tpath() {
  }

  virtual ~NfsRpc_xmp_getattr_args() throw();
  std::string tpath;
  thrift_stat stbuf;

  _NfsRpc_xmp_getattr_args__isset __isset;

  void __set_tpath(const std::string& val);

  void __set_stbuf(const thrift_stat& val);

  bool operator == (const NfsRpc_xmp_getattr_args & rhs) const
  {
    if (!(tpath == rhs.tpath))
      return false;
    if (!(stbuf == rhs.stbuf))
      return false;
    return true;
  }
  bool operator != (const NfsRpc_xmp_getattr_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const NfsRpc_xmp_getattr_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class NfsRpc_xmp_getattr_pargs {
 public:


  virtual ~NfsRpc_xmp_getattr_pargs() throw();
  const std::string* tpath;
  const thrift_stat* stbuf;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _NfsRpc_xmp_getattr_result__isset {
  _NfsRpc_xmp_getattr_result__isset() : success(false) {}
  bool success :1;
} _NfsRpc_xmp_getattr_result__isset;

class NfsRpc_xmp_getattr_result {
 public:

  NfsRpc_xmp_getattr_result(const NfsRpc_xmp_getattr_result&);
  NfsRpc_xmp_getattr_result& operator=(const NfsRpc_xmp_getattr_result&);
  NfsRpc_xmp_getattr_result() {
  }

  virtual ~NfsRpc_xmp_getattr_result() throw();
  thrift_getattr_reply success;

  _NfsRpc_xmp_getattr_result__isset __isset;

  void __set_success(const thrift_getattr_reply& val);

  bool operator == (const NfsRpc_xmp_getattr_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const NfsRpc_xmp_getattr_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const NfsRpc_xmp_getattr_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _NfsRpc_xmp_getattr_presult__isset {
  _NfsRpc_xmp_getattr_presult__isset() : success(false) {}
  bool success :1;
} _NfsRpc_xmp_getattr_presult__isset;

class NfsRpc_xmp_getattr_presult {
 public:


  virtual ~NfsRpc_xmp_getattr_presult() throw();
  thrift_getattr_reply* success;

  _NfsRpc_xmp_getattr_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _NfsRpc_xmp_setattr_args__isset {
  _NfsRpc_xmp_setattr_args__isset() : tpath(false), stbuf(false) {}
  bool tpath :1;
  bool stbuf :1;
} _NfsRpc_xmp_setattr_args__isset;

class NfsRpc_xmp_setattr_args {
 public:

  NfsRpc_xmp_setattr_args(const NfsRpc_xmp_setattr_args&);
  NfsRpc_xmp_setattr_args& operator=(const NfsRpc_xmp_setattr_args&);
  NfsRpc_xmp_setattr_args() : tpath() {
  }

  virtual ~NfsRpc_xmp_setattr_args() throw();
  std::string tpath;
  thrift_stat stbuf;

  _NfsRpc_xmp_setattr_args__isset __isset;

  void __set_tpath(const std::string& val);

  void __set_stbuf(const thrift_stat& val);

  bool operator == (const NfsRpc_xmp_setattr_args & rhs) const
  {
    if (!(tpath == rhs.tpath))
      return false;
    if (!(stbuf == rhs.stbuf))
      return false;
    return true;
  }
  bool operator != (const NfsRpc_xmp_setattr_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const NfsRpc_xmp_setattr_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class NfsRpc_xmp_setattr_pargs {
 public:


  virtual ~NfsRpc_xmp_setattr_pargs() throw();
  const std::string* tpath;
  const thrift_stat* stbuf;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _NfsRpc_xmp_setattr_result__isset {
  _NfsRpc_xmp_setattr_result__isset() : success(false) {}
  bool success :1;
} _NfsRpc_xmp_setattr_result__isset;

class NfsRpc_xmp_setattr_result {
 public:

  NfsRpc_xmp_setattr_result(const NfsRpc_xmp_setattr_result&);
  NfsRpc_xmp_setattr_result& operator=(const NfsRpc_xmp_setattr_result&);
  NfsRpc_xmp_setattr_result() : success(0) {
  }

  virtual ~NfsRpc_xmp_setattr_result() throw();
  int32_t success;

  _NfsRpc_xmp_setattr_result__isset __isset;

  void __set_success(const int32_t val);

  bool operator == (const NfsRpc_xmp_setattr_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const NfsRpc_xmp_setattr_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const NfsRpc_xmp_setattr_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _NfsRpc_xmp_setattr_presult__isset {
  _NfsRpc_xmp_setattr_presult__isset() : success(false) {}
  bool success :1;
} _NfsRpc_xmp_setattr_presult__isset;

class NfsRpc_xmp_setattr_presult {
 public:


  virtual ~NfsRpc_xmp_setattr_presult() throw();
  int32_t* success;

  _NfsRpc_xmp_setattr_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _NfsRpc_xmp_read_args__isset {
  _NfsRpc_xmp_read_args__isset() : tpath(false), tbuf(false), size(false), offset(false), tfi(false) {}
  bool tpath :1;
  bool tbuf :1;
  bool size :1;
  bool offset :1;
  bool tfi :1;
} _NfsRpc_xmp_read_args__isset;

class NfsRpc_xmp_read_args {
 public:

  NfsRpc_xmp_read_args(const NfsRpc_xmp_read_args&);
  NfsRpc_xmp_read_args& operator=(const NfsRpc_xmp_read_args&);
  NfsRpc_xmp_read_args() : tpath(), tbuf(), size(0), offset(0) {
  }

  virtual ~NfsRpc_xmp_read_args() throw();
  std::string tpath;
  std::string tbuf;
  int64_t size;
  int64_t offset;
  thrift_fuse_file_info tfi;

  _NfsRpc_xmp_read_args__isset __isset;

  void __set_tpath(const std::string& val);

  void __set_tbuf(const std::string& val);

  void __set_size(const int64_t val);

  void __set_offset(const int64_t val);

  void __set_tfi(const thrift_fuse_file_info& val);

  bool operator == (const NfsRpc_xmp_read_args & rhs) const
  {
    if (!(tpath == rhs.tpath))
      return false;
    if (!(tbuf == rhs.tbuf))
      return false;
    if (!(size == rhs.size))
      return false;
    if (!(offset == rhs.offset))
      return false;
    if (!(tfi == rhs.tfi))
      return false;
    return true;
  }
  bool operator != (const NfsRpc_xmp_read_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const NfsRpc_xmp_read_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class NfsRpc_xmp_read_pargs {
 public:


  virtual ~NfsRpc_xmp_read_pargs() throw();
  const std::string* tpath;
  const std::string* tbuf;
  const int64_t* size;
  const int64_t* offset;
  const thrift_fuse_file_info* tfi;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _NfsRpc_xmp_read_result__isset {
  _NfsRpc_xmp_read_result__isset() : success(false) {}
  bool success :1;
} _NfsRpc_xmp_read_result__isset;

class NfsRpc_xmp_read_result {
 public:

  NfsRpc_xmp_read_result(const NfsRpc_xmp_read_result&);
  NfsRpc_xmp_read_result& operator=(const NfsRpc_xmp_read_result&);
  NfsRpc_xmp_read_result() {
  }

  virtual ~NfsRpc_xmp_read_result() throw();
  thrift_read_reply success;

  _NfsRpc_xmp_read_result__isset __isset;

  void __set_success(const thrift_read_reply& val);

  bool operator == (const NfsRpc_xmp_read_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const NfsRpc_xmp_read_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const NfsRpc_xmp_read_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _NfsRpc_xmp_read_presult__isset {
  _NfsRpc_xmp_read_presult__isset() : success(false) {}
  bool success :1;
} _NfsRpc_xmp_read_presult__isset;

class NfsRpc_xmp_read_presult {
 public:


  virtual ~NfsRpc_xmp_read_presult() throw();
  thrift_read_reply* success;

  _NfsRpc_xmp_read_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _NfsRpc_xmp_write_args__isset {
  _NfsRpc_xmp_write_args__isset() : tpath(false), tbuf(false), size(false), offset(false), tfi(false) {}
  bool tpath :1;
  bool tbuf :1;
  bool size :1;
  bool offset :1;
  bool tfi :1;
} _NfsRpc_xmp_write_args__isset;

class NfsRpc_xmp_write_args {
 public:

  NfsRpc_xmp_write_args(const NfsRpc_xmp_write_args&);
  NfsRpc_xmp_write_args& operator=(const NfsRpc_xmp_write_args&);
  NfsRpc_xmp_write_args() : tpath(), tbuf(), size(0), offset(0) {
  }

  virtual ~NfsRpc_xmp_write_args() throw();
  std::string tpath;
  std::string tbuf;
  int64_t size;
  int64_t offset;
  thrift_fuse_file_info tfi;

  _NfsRpc_xmp_write_args__isset __isset;

  void __set_tpath(const std::string& val);

  void __set_tbuf(const std::string& val);

  void __set_size(const int64_t val);

  void __set_offset(const int64_t val);

  void __set_tfi(const thrift_fuse_file_info& val);

  bool operator == (const NfsRpc_xmp_write_args & rhs) const
  {
    if (!(tpath == rhs.tpath))
      return false;
    if (!(tbuf == rhs.tbuf))
      return false;
    if (!(size == rhs.size))
      return false;
    if (!(offset == rhs.offset))
      return false;
    if (!(tfi == rhs.tfi))
      return false;
    return true;
  }
  bool operator != (const NfsRpc_xmp_write_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const NfsRpc_xmp_write_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class NfsRpc_xmp_write_pargs {
 public:


  virtual ~NfsRpc_xmp_write_pargs() throw();
  const std::string* tpath;
  const std::string* tbuf;
  const int64_t* size;
  const int64_t* offset;
  const thrift_fuse_file_info* tfi;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _NfsRpc_xmp_write_result__isset {
  _NfsRpc_xmp_write_result__isset() : success(false) {}
  bool success :1;
} _NfsRpc_xmp_write_result__isset;

class NfsRpc_xmp_write_result {
 public:

  NfsRpc_xmp_write_result(const NfsRpc_xmp_write_result&);
  NfsRpc_xmp_write_result& operator=(const NfsRpc_xmp_write_result&);
  NfsRpc_xmp_write_result() : success(0) {
  }

  virtual ~NfsRpc_xmp_write_result() throw();
  int32_t success;

  _NfsRpc_xmp_write_result__isset __isset;

  void __set_success(const int32_t val);

  bool operator == (const NfsRpc_xmp_write_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const NfsRpc_xmp_write_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const NfsRpc_xmp_write_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _NfsRpc_xmp_write_presult__isset {
  _NfsRpc_xmp_write_presult__isset() : success(false) {}
  bool success :1;
} _NfsRpc_xmp_write_presult__isset;

class NfsRpc_xmp_write_presult {
 public:


  virtual ~NfsRpc_xmp_write_presult() throw();
  int32_t* success;

  _NfsRpc_xmp_write_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _NfsRpc_xmp_rename_args__isset {
  _NfsRpc_xmp_rename_args__isset() : tfrom(false), tto(false) {}
  bool tfrom :1;
  bool tto :1;
} _NfsRpc_xmp_rename_args__isset;

class NfsRpc_xmp_rename_args {
 public:

  NfsRpc_xmp_rename_args(const NfsRpc_xmp_rename_args&);
  NfsRpc_xmp_rename_args& operator=(const NfsRpc_xmp_rename_args&);
  NfsRpc_xmp_rename_args() : tfrom(), tto() {
  }

  virtual ~NfsRpc_xmp_rename_args() throw();
  std::string tfrom;
  std::string tto;

  _NfsRpc_xmp_rename_args__isset __isset;

  void __set_tfrom(const std::string& val);

  void __set_tto(const std::string& val);

  bool operator == (const NfsRpc_xmp_rename_args & rhs) const
  {
    if (!(tfrom == rhs.tfrom))
      return false;
    if (!(tto == rhs.tto))
      return false;
    return true;
  }
  bool operator != (const NfsRpc_xmp_rename_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const NfsRpc_xmp_rename_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class NfsRpc_xmp_rename_pargs {
 public:


  virtual ~NfsRpc_xmp_rename_pargs() throw();
  const std::string* tfrom;
  const std::string* tto;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _NfsRpc_xmp_rename_result__isset {
  _NfsRpc_xmp_rename_result__isset() : success(false) {}
  bool success :1;
} _NfsRpc_xmp_rename_result__isset;

class NfsRpc_xmp_rename_result {
 public:

  NfsRpc_xmp_rename_result(const NfsRpc_xmp_rename_result&);
  NfsRpc_xmp_rename_result& operator=(const NfsRpc_xmp_rename_result&);
  NfsRpc_xmp_rename_result() : success(0) {
  }

  virtual ~NfsRpc_xmp_rename_result() throw();
  int32_t success;

  _NfsRpc_xmp_rename_result__isset __isset;

  void __set_success(const int32_t val);

  bool operator == (const NfsRpc_xmp_rename_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const NfsRpc_xmp_rename_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const NfsRpc_xmp_rename_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _NfsRpc_xmp_rename_presult__isset {
  _NfsRpc_xmp_rename_presult__isset() : success(false) {}
  bool success :1;
} _NfsRpc_xmp_rename_presult__isset;

class NfsRpc_xmp_rename_presult {
 public:


  virtual ~NfsRpc_xmp_rename_presult() throw();
  int32_t* success;

  _NfsRpc_xmp_rename_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _NfsRpc_xmp_mkdir_args__isset {
  _NfsRpc_xmp_mkdir_args__isset() : tpath(false), mode(false) {}
  bool tpath :1;
  bool mode :1;
} _NfsRpc_xmp_mkdir_args__isset;

class NfsRpc_xmp_mkdir_args {
 public:

  NfsRpc_xmp_mkdir_args(const NfsRpc_xmp_mkdir_args&);
  NfsRpc_xmp_mkdir_args& operator=(const NfsRpc_xmp_mkdir_args&);
  NfsRpc_xmp_mkdir_args() : tpath(), mode(0) {
  }

  virtual ~NfsRpc_xmp_mkdir_args() throw();
  std::string tpath;
  int32_t mode;

  _NfsRpc_xmp_mkdir_args__isset __isset;

  void __set_tpath(const std::string& val);

  void __set_mode(const int32_t val);

  bool operator == (const NfsRpc_xmp_mkdir_args & rhs) const
  {
    if (!(tpath == rhs.tpath))
      return false;
    if (!(mode == rhs.mode))
      return false;
    return true;
  }
  bool operator != (const NfsRpc_xmp_mkdir_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const NfsRpc_xmp_mkdir_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class NfsRpc_xmp_mkdir_pargs {
 public:


  virtual ~NfsRpc_xmp_mkdir_pargs() throw();
  const std::string* tpath;
  const int32_t* mode;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _NfsRpc_xmp_mkdir_result__isset {
  _NfsRpc_xmp_mkdir_result__isset() : success(false) {}
  bool success :1;
} _NfsRpc_xmp_mkdir_result__isset;

class NfsRpc_xmp_mkdir_result {
 public:

  NfsRpc_xmp_mkdir_result(const NfsRpc_xmp_mkdir_result&);
  NfsRpc_xmp_mkdir_result& operator=(const NfsRpc_xmp_mkdir_result&);
  NfsRpc_xmp_mkdir_result() : success(0) {
  }

  virtual ~NfsRpc_xmp_mkdir_result() throw();
  int32_t success;

  _NfsRpc_xmp_mkdir_result__isset __isset;

  void __set_success(const int32_t val);

  bool operator == (const NfsRpc_xmp_mkdir_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const NfsRpc_xmp_mkdir_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const NfsRpc_xmp_mkdir_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _NfsRpc_xmp_mkdir_presult__isset {
  _NfsRpc_xmp_mkdir_presult__isset() : success(false) {}
  bool success :1;
} _NfsRpc_xmp_mkdir_presult__isset;

class NfsRpc_xmp_mkdir_presult {
 public:


  virtual ~NfsRpc_xmp_mkdir_presult() throw();
  int32_t* success;

  _NfsRpc_xmp_mkdir_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _NfsRpc_xmp_rmdir_args__isset {
  _NfsRpc_xmp_rmdir_args__isset() : tpath(false) {}
  bool tpath :1;
} _NfsRpc_xmp_rmdir_args__isset;

class NfsRpc_xmp_rmdir_args {
 public:

  NfsRpc_xmp_rmdir_args(const NfsRpc_xmp_rmdir_args&);
  NfsRpc_xmp_rmdir_args& operator=(const NfsRpc_xmp_rmdir_args&);
  NfsRpc_xmp_rmdir_args() : tpath() {
  }

  virtual ~NfsRpc_xmp_rmdir_args() throw();
  std::string tpath;

  _NfsRpc_xmp_rmdir_args__isset __isset;

  void __set_tpath(const std::string& val);

  bool operator == (const NfsRpc_xmp_rmdir_args & rhs) const
  {
    if (!(tpath == rhs.tpath))
      return false;
    return true;
  }
  bool operator != (const NfsRpc_xmp_rmdir_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const NfsRpc_xmp_rmdir_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class NfsRpc_xmp_rmdir_pargs {
 public:


  virtual ~NfsRpc_xmp_rmdir_pargs() throw();
  const std::string* tpath;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _NfsRpc_xmp_rmdir_result__isset {
  _NfsRpc_xmp_rmdir_result__isset() : success(false) {}
  bool success :1;
} _NfsRpc_xmp_rmdir_result__isset;

class NfsRpc_xmp_rmdir_result {
 public:

  NfsRpc_xmp_rmdir_result(const NfsRpc_xmp_rmdir_result&);
  NfsRpc_xmp_rmdir_result& operator=(const NfsRpc_xmp_rmdir_result&);
  NfsRpc_xmp_rmdir_result() : success(0) {
  }

  virtual ~NfsRpc_xmp_rmdir_result() throw();
  int32_t success;

  _NfsRpc_xmp_rmdir_result__isset __isset;

  void __set_success(const int32_t val);

  bool operator == (const NfsRpc_xmp_rmdir_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const NfsRpc_xmp_rmdir_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const NfsRpc_xmp_rmdir_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _NfsRpc_xmp_rmdir_presult__isset {
  _NfsRpc_xmp_rmdir_presult__isset() : success(false) {}
  bool success :1;
} _NfsRpc_xmp_rmdir_presult__isset;

class NfsRpc_xmp_rmdir_presult {
 public:


  virtual ~NfsRpc_xmp_rmdir_presult() throw();
  int32_t* success;

  _NfsRpc_xmp_rmdir_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _NfsRpc_xmp_statfs_args__isset {
  _NfsRpc_xmp_statfs_args__isset() : tpath(false), tstbuf(false) {}
  bool tpath :1;
  bool tstbuf :1;
} _NfsRpc_xmp_statfs_args__isset;

class NfsRpc_xmp_statfs_args {
 public:

  NfsRpc_xmp_statfs_args(const NfsRpc_xmp_statfs_args&);
  NfsRpc_xmp_statfs_args& operator=(const NfsRpc_xmp_statfs_args&);
  NfsRpc_xmp_statfs_args() : tpath() {
  }

  virtual ~NfsRpc_xmp_statfs_args() throw();
  std::string tpath;
  thrift_statvfs tstbuf;

  _NfsRpc_xmp_statfs_args__isset __isset;

  void __set_tpath(const std::string& val);

  void __set_tstbuf(const thrift_statvfs& val);

  bool operator == (const NfsRpc_xmp_statfs_args & rhs) const
  {
    if (!(tpath == rhs.tpath))
      return false;
    if (!(tstbuf == rhs.tstbuf))
      return false;
    return true;
  }
  bool operator != (const NfsRpc_xmp_statfs_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const NfsRpc_xmp_statfs_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class NfsRpc_xmp_statfs_pargs {
 public:


  virtual ~NfsRpc_xmp_statfs_pargs() throw();
  const std::string* tpath;
  const thrift_statvfs* tstbuf;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _NfsRpc_xmp_statfs_result__isset {
  _NfsRpc_xmp_statfs_result__isset() : success(false) {}
  bool success :1;
} _NfsRpc_xmp_statfs_result__isset;

class NfsRpc_xmp_statfs_result {
 public:

  NfsRpc_xmp_statfs_result(const NfsRpc_xmp_statfs_result&);
  NfsRpc_xmp_statfs_result& operator=(const NfsRpc_xmp_statfs_result&);
  NfsRpc_xmp_statfs_result() {
  }

  virtual ~NfsRpc_xmp_statfs_result() throw();
  thrift_statfs_reply success;

  _NfsRpc_xmp_statfs_result__isset __isset;

  void __set_success(const thrift_statfs_reply& val);

  bool operator == (const NfsRpc_xmp_statfs_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const NfsRpc_xmp_statfs_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const NfsRpc_xmp_statfs_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _NfsRpc_xmp_statfs_presult__isset {
  _NfsRpc_xmp_statfs_presult__isset() : success(false) {}
  bool success :1;
} _NfsRpc_xmp_statfs_presult__isset;

class NfsRpc_xmp_statfs_presult {
 public:


  virtual ~NfsRpc_xmp_statfs_presult() throw();
  thrift_statfs_reply* success;

  _NfsRpc_xmp_statfs_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _NfsRpc_xmp_open_args__isset {
  _NfsRpc_xmp_open_args__isset() : tpath(false), tfi(false) {}
  bool tpath :1;
  bool tfi :1;
} _NfsRpc_xmp_open_args__isset;

class NfsRpc_xmp_open_args {
 public:

  NfsRpc_xmp_open_args(const NfsRpc_xmp_open_args&);
  NfsRpc_xmp_open_args& operator=(const NfsRpc_xmp_open_args&);
  NfsRpc_xmp_open_args() : tpath() {
  }

  virtual ~NfsRpc_xmp_open_args() throw();
  std::string tpath;
  thrift_fuse_file_info tfi;

  _NfsRpc_xmp_open_args__isset __isset;

  void __set_tpath(const std::string& val);

  void __set_tfi(const thrift_fuse_file_info& val);

  bool operator == (const NfsRpc_xmp_open_args & rhs) const
  {
    if (!(tpath == rhs.tpath))
      return false;
    if (!(tfi == rhs.tfi))
      return false;
    return true;
  }
  bool operator != (const NfsRpc_xmp_open_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const NfsRpc_xmp_open_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class NfsRpc_xmp_open_pargs {
 public:


  virtual ~NfsRpc_xmp_open_pargs() throw();
  const std::string* tpath;
  const thrift_fuse_file_info* tfi;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _NfsRpc_xmp_open_result__isset {
  _NfsRpc_xmp_open_result__isset() : success(false) {}
  bool success :1;
} _NfsRpc_xmp_open_result__isset;

class NfsRpc_xmp_open_result {
 public:

  NfsRpc_xmp_open_result(const NfsRpc_xmp_open_result&);
  NfsRpc_xmp_open_result& operator=(const NfsRpc_xmp_open_result&);
  NfsRpc_xmp_open_result() {
  }

  virtual ~NfsRpc_xmp_open_result() throw();
  thrift_open_reply success;

  _NfsRpc_xmp_open_result__isset __isset;

  void __set_success(const thrift_open_reply& val);

  bool operator == (const NfsRpc_xmp_open_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const NfsRpc_xmp_open_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const NfsRpc_xmp_open_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _NfsRpc_xmp_open_presult__isset {
  _NfsRpc_xmp_open_presult__isset() : success(false) {}
  bool success :1;
} _NfsRpc_xmp_open_presult__isset;

class NfsRpc_xmp_open_presult {
 public:


  virtual ~NfsRpc_xmp_open_presult() throw();
  thrift_open_reply* success;

  _NfsRpc_xmp_open_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _NfsRpc_xmp_access_args__isset {
  _NfsRpc_xmp_access_args__isset() : tpath(false), mask(false) {}
  bool tpath :1;
  bool mask :1;
} _NfsRpc_xmp_access_args__isset;

class NfsRpc_xmp_access_args {
 public:

  NfsRpc_xmp_access_args(const NfsRpc_xmp_access_args&);
  NfsRpc_xmp_access_args& operator=(const NfsRpc_xmp_access_args&);
  NfsRpc_xmp_access_args() : tpath(), mask(0) {
  }

  virtual ~NfsRpc_xmp_access_args() throw();
  std::string tpath;
  int32_t mask;

  _NfsRpc_xmp_access_args__isset __isset;

  void __set_tpath(const std::string& val);

  void __set_mask(const int32_t val);

  bool operator == (const NfsRpc_xmp_access_args & rhs) const
  {
    if (!(tpath == rhs.tpath))
      return false;
    if (!(mask == rhs.mask))
      return false;
    return true;
  }
  bool operator != (const NfsRpc_xmp_access_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const NfsRpc_xmp_access_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class NfsRpc_xmp_access_pargs {
 public:


  virtual ~NfsRpc_xmp_access_pargs() throw();
  const std::string* tpath;
  const int32_t* mask;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _NfsRpc_xmp_access_result__isset {
  _NfsRpc_xmp_access_result__isset() : success(false) {}
  bool success :1;
} _NfsRpc_xmp_access_result__isset;

class NfsRpc_xmp_access_result {
 public:

  NfsRpc_xmp_access_result(const NfsRpc_xmp_access_result&);
  NfsRpc_xmp_access_result& operator=(const NfsRpc_xmp_access_result&);
  NfsRpc_xmp_access_result() : success(0) {
  }

  virtual ~NfsRpc_xmp_access_result() throw();
  int32_t success;

  _NfsRpc_xmp_access_result__isset __isset;

  void __set_success(const int32_t val);

  bool operator == (const NfsRpc_xmp_access_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const NfsRpc_xmp_access_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const NfsRpc_xmp_access_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _NfsRpc_xmp_access_presult__isset {
  _NfsRpc_xmp_access_presult__isset() : success(false) {}
  bool success :1;
} _NfsRpc_xmp_access_presult__isset;

class NfsRpc_xmp_access_presult {
 public:


  virtual ~NfsRpc_xmp_access_presult() throw();
  int32_t* success;

  _NfsRpc_xmp_access_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _NfsRpc_xmp_mknod_args__isset {
  _NfsRpc_xmp_mknod_args__isset() : tpath(false), mode(false), rdev(false) {}
  bool tpath :1;
  bool mode :1;
  bool rdev :1;
} _NfsRpc_xmp_mknod_args__isset;

class NfsRpc_xmp_mknod_args {
 public:

  NfsRpc_xmp_mknod_args(const NfsRpc_xmp_mknod_args&);
  NfsRpc_xmp_mknod_args& operator=(const NfsRpc_xmp_mknod_args&);
  NfsRpc_xmp_mknod_args() : tpath(), mode(0), rdev(0) {
  }

  virtual ~NfsRpc_xmp_mknod_args() throw();
  std::string tpath;
  int32_t mode;
  int64_t rdev;

  _NfsRpc_xmp_mknod_args__isset __isset;

  void __set_tpath(const std::string& val);

  void __set_mode(const int32_t val);

  void __set_rdev(const int64_t val);

  bool operator == (const NfsRpc_xmp_mknod_args & rhs) const
  {
    if (!(tpath == rhs.tpath))
      return false;
    if (!(mode == rhs.mode))
      return false;
    if (!(rdev == rhs.rdev))
      return false;
    return true;
  }
  bool operator != (const NfsRpc_xmp_mknod_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const NfsRpc_xmp_mknod_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class NfsRpc_xmp_mknod_pargs {
 public:


  virtual ~NfsRpc_xmp_mknod_pargs() throw();
  const std::string* tpath;
  const int32_t* mode;
  const int64_t* rdev;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _NfsRpc_xmp_mknod_result__isset {
  _NfsRpc_xmp_mknod_result__isset() : success(false) {}
  bool success :1;
} _NfsRpc_xmp_mknod_result__isset;

class NfsRpc_xmp_mknod_result {
 public:

  NfsRpc_xmp_mknod_result(const NfsRpc_xmp_mknod_result&);
  NfsRpc_xmp_mknod_result& operator=(const NfsRpc_xmp_mknod_result&);
  NfsRpc_xmp_mknod_result() : success(0) {
  }

  virtual ~NfsRpc_xmp_mknod_result() throw();
  int32_t success;

  _NfsRpc_xmp_mknod_result__isset __isset;

  void __set_success(const int32_t val);

  bool operator == (const NfsRpc_xmp_mknod_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const NfsRpc_xmp_mknod_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const NfsRpc_xmp_mknod_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _NfsRpc_xmp_mknod_presult__isset {
  _NfsRpc_xmp_mknod_presult__isset() : success(false) {}
  bool success :1;
} _NfsRpc_xmp_mknod_presult__isset;

class NfsRpc_xmp_mknod_presult {
 public:


  virtual ~NfsRpc_xmp_mknod_presult() throw();
  int32_t* success;

  _NfsRpc_xmp_mknod_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class NfsRpcClient : virtual public NfsRpcIf {
 public:
    NfsRpcClient(){}
  NfsRpcClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  NfsRpcClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  int32_t xmp_create(const std::string& tpath, const int32_t mode, const thrift_fuse_file_info& tfi);
  void send_xmp_create(const std::string& tpath, const int32_t mode, const thrift_fuse_file_info& tfi);
  int32_t recv_xmp_create();
  int32_t xmp_unlink(const std::string& tpath);
  void send_xmp_unlink(const std::string& tpath);
  int32_t recv_xmp_unlink();
  void xmp_getattr(thrift_getattr_reply& _return, const std::string& tpath, const thrift_stat& stbuf);
  void send_xmp_getattr(const std::string& tpath, const thrift_stat& stbuf);
  void recv_xmp_getattr(thrift_getattr_reply& _return);
  int32_t xmp_setattr(const std::string& tpath, const thrift_stat& stbuf);
  void send_xmp_setattr(const std::string& tpath, const thrift_stat& stbuf);
  int32_t recv_xmp_setattr();
  void xmp_read(thrift_read_reply& _return, const std::string& tpath, const std::string& tbuf, const int64_t size, const int64_t offset, const thrift_fuse_file_info& tfi);
  void send_xmp_read(const std::string& tpath, const std::string& tbuf, const int64_t size, const int64_t offset, const thrift_fuse_file_info& tfi);
  void recv_xmp_read(thrift_read_reply& _return);
  int32_t xmp_write(const std::string& tpath, const std::string& tbuf, const int64_t size, const int64_t offset, const thrift_fuse_file_info& tfi);
  void send_xmp_write(const std::string& tpath, const std::string& tbuf, const int64_t size, const int64_t offset, const thrift_fuse_file_info& tfi);
  int32_t recv_xmp_write();
  int32_t xmp_rename(const std::string& tfrom, const std::string& tto);
  void send_xmp_rename(const std::string& tfrom, const std::string& tto);
  int32_t recv_xmp_rename();
  int32_t xmp_mkdir(const std::string& tpath, const int32_t mode);
  void send_xmp_mkdir(const std::string& tpath, const int32_t mode);
  int32_t recv_xmp_mkdir();
  int32_t xmp_rmdir(const std::string& tpath);
  void send_xmp_rmdir(const std::string& tpath);
  int32_t recv_xmp_rmdir();
  void xmp_statfs(thrift_statfs_reply& _return, const std::string& tpath, const thrift_statvfs& tstbuf);
  void send_xmp_statfs(const std::string& tpath, const thrift_statvfs& tstbuf);
  void recv_xmp_statfs(thrift_statfs_reply& _return);
  void xmp_open(thrift_open_reply& _return, const std::string& tpath, const thrift_fuse_file_info& tfi);
  void send_xmp_open(const std::string& tpath, const thrift_fuse_file_info& tfi);
  void recv_xmp_open(thrift_open_reply& _return);
  int32_t xmp_access(const std::string& tpath, const int32_t mask);
  void send_xmp_access(const std::string& tpath, const int32_t mask);
  int32_t recv_xmp_access();
  int32_t xmp_mknod(const std::string& tpath, const int32_t mode, const int64_t rdev);
  void send_xmp_mknod(const std::string& tpath, const int32_t mode, const int64_t rdev);
  int32_t recv_xmp_mknod();
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class NfsRpcProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<NfsRpcIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (NfsRpcProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_xmp_create(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_xmp_unlink(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_xmp_getattr(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_xmp_setattr(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_xmp_read(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_xmp_write(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_xmp_rename(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_xmp_mkdir(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_xmp_rmdir(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_xmp_statfs(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_xmp_open(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_xmp_access(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_xmp_mknod(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  NfsRpcProcessor(boost::shared_ptr<NfsRpcIf> iface) :
    iface_(iface) {
    processMap_["xmp_create"] = &NfsRpcProcessor::process_xmp_create;
    processMap_["xmp_unlink"] = &NfsRpcProcessor::process_xmp_unlink;
    processMap_["xmp_getattr"] = &NfsRpcProcessor::process_xmp_getattr;
    processMap_["xmp_setattr"] = &NfsRpcProcessor::process_xmp_setattr;
    processMap_["xmp_read"] = &NfsRpcProcessor::process_xmp_read;
    processMap_["xmp_write"] = &NfsRpcProcessor::process_xmp_write;
    processMap_["xmp_rename"] = &NfsRpcProcessor::process_xmp_rename;
    processMap_["xmp_mkdir"] = &NfsRpcProcessor::process_xmp_mkdir;
    processMap_["xmp_rmdir"] = &NfsRpcProcessor::process_xmp_rmdir;
    processMap_["xmp_statfs"] = &NfsRpcProcessor::process_xmp_statfs;
    processMap_["xmp_open"] = &NfsRpcProcessor::process_xmp_open;
    processMap_["xmp_access"] = &NfsRpcProcessor::process_xmp_access;
    processMap_["xmp_mknod"] = &NfsRpcProcessor::process_xmp_mknod;
  }

  virtual ~NfsRpcProcessor() {}
};

class NfsRpcProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  NfsRpcProcessorFactory(const ::boost::shared_ptr< NfsRpcIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< NfsRpcIfFactory > handlerFactory_;
};

class NfsRpcMultiface : virtual public NfsRpcIf {
 public:
  NfsRpcMultiface(std::vector<boost::shared_ptr<NfsRpcIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~NfsRpcMultiface() {}
 protected:
  std::vector<boost::shared_ptr<NfsRpcIf> > ifaces_;
  NfsRpcMultiface() {}
  void add(boost::shared_ptr<NfsRpcIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  int32_t xmp_create(const std::string& tpath, const int32_t mode, const thrift_fuse_file_info& tfi) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->xmp_create(tpath, mode, tfi);
    }
    return ifaces_[i]->xmp_create(tpath, mode, tfi);
  }

  int32_t xmp_unlink(const std::string& tpath) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->xmp_unlink(tpath);
    }
    return ifaces_[i]->xmp_unlink(tpath);
  }

  void xmp_getattr(thrift_getattr_reply& _return, const std::string& tpath, const thrift_stat& stbuf) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->xmp_getattr(_return, tpath, stbuf);
    }
    ifaces_[i]->xmp_getattr(_return, tpath, stbuf);
    return;
  }

  int32_t xmp_setattr(const std::string& tpath, const thrift_stat& stbuf) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->xmp_setattr(tpath, stbuf);
    }
    return ifaces_[i]->xmp_setattr(tpath, stbuf);
  }

  void xmp_read(thrift_read_reply& _return, const std::string& tpath, const std::string& tbuf, const int64_t size, const int64_t offset, const thrift_fuse_file_info& tfi) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->xmp_read(_return, tpath, tbuf, size, offset, tfi);
    }
    ifaces_[i]->xmp_read(_return, tpath, tbuf, size, offset, tfi);
    return;
  }

  int32_t xmp_write(const std::string& tpath, const std::string& tbuf, const int64_t size, const int64_t offset, const thrift_fuse_file_info& tfi) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->xmp_write(tpath, tbuf, size, offset, tfi);
    }
    return ifaces_[i]->xmp_write(tpath, tbuf, size, offset, tfi);
  }

  int32_t xmp_rename(const std::string& tfrom, const std::string& tto) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->xmp_rename(tfrom, tto);
    }
    return ifaces_[i]->xmp_rename(tfrom, tto);
  }

  int32_t xmp_mkdir(const std::string& tpath, const int32_t mode) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->xmp_mkdir(tpath, mode);
    }
    return ifaces_[i]->xmp_mkdir(tpath, mode);
  }

  int32_t xmp_rmdir(const std::string& tpath) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->xmp_rmdir(tpath);
    }
    return ifaces_[i]->xmp_rmdir(tpath);
  }

  void xmp_statfs(thrift_statfs_reply& _return, const std::string& tpath, const thrift_statvfs& tstbuf) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->xmp_statfs(_return, tpath, tstbuf);
    }
    ifaces_[i]->xmp_statfs(_return, tpath, tstbuf);
    return;
  }

  void xmp_open(thrift_open_reply& _return, const std::string& tpath, const thrift_fuse_file_info& tfi) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->xmp_open(_return, tpath, tfi);
    }
    ifaces_[i]->xmp_open(_return, tpath, tfi);
    return;
  }

  int32_t xmp_access(const std::string& tpath, const int32_t mask) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->xmp_access(tpath, mask);
    }
    return ifaces_[i]->xmp_access(tpath, mask);
  }

  int32_t xmp_mknod(const std::string& tpath, const int32_t mode, const int64_t rdev) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->xmp_mknod(tpath, mode, rdev);
    }
    return ifaces_[i]->xmp_mknod(tpath, mode, rdev);
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class NfsRpcConcurrentClient : virtual public NfsRpcIf {
 public:
  NfsRpcConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  NfsRpcConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  int32_t xmp_create(const std::string& tpath, const int32_t mode, const thrift_fuse_file_info& tfi);
  int32_t send_xmp_create(const std::string& tpath, const int32_t mode, const thrift_fuse_file_info& tfi);
  int32_t recv_xmp_create(const int32_t seqid);
  int32_t xmp_unlink(const std::string& tpath);
  int32_t send_xmp_unlink(const std::string& tpath);
  int32_t recv_xmp_unlink(const int32_t seqid);
  void xmp_getattr(thrift_getattr_reply& _return, const std::string& tpath, const thrift_stat& stbuf);
  int32_t send_xmp_getattr(const std::string& tpath, const thrift_stat& stbuf);
  void recv_xmp_getattr(thrift_getattr_reply& _return, const int32_t seqid);
  int32_t xmp_setattr(const std::string& tpath, const thrift_stat& stbuf);
  int32_t send_xmp_setattr(const std::string& tpath, const thrift_stat& stbuf);
  int32_t recv_xmp_setattr(const int32_t seqid);
  void xmp_read(thrift_read_reply& _return, const std::string& tpath, const std::string& tbuf, const int64_t size, const int64_t offset, const thrift_fuse_file_info& tfi);
  int32_t send_xmp_read(const std::string& tpath, const std::string& tbuf, const int64_t size, const int64_t offset, const thrift_fuse_file_info& tfi);
  void recv_xmp_read(thrift_read_reply& _return, const int32_t seqid);
  int32_t xmp_write(const std::string& tpath, const std::string& tbuf, const int64_t size, const int64_t offset, const thrift_fuse_file_info& tfi);
  int32_t send_xmp_write(const std::string& tpath, const std::string& tbuf, const int64_t size, const int64_t offset, const thrift_fuse_file_info& tfi);
  int32_t recv_xmp_write(const int32_t seqid);
  int32_t xmp_rename(const std::string& tfrom, const std::string& tto);
  int32_t send_xmp_rename(const std::string& tfrom, const std::string& tto);
  int32_t recv_xmp_rename(const int32_t seqid);
  int32_t xmp_mkdir(const std::string& tpath, const int32_t mode);
  int32_t send_xmp_mkdir(const std::string& tpath, const int32_t mode);
  int32_t recv_xmp_mkdir(const int32_t seqid);
  int32_t xmp_rmdir(const std::string& tpath);
  int32_t send_xmp_rmdir(const std::string& tpath);
  int32_t recv_xmp_rmdir(const int32_t seqid);
  void xmp_statfs(thrift_statfs_reply& _return, const std::string& tpath, const thrift_statvfs& tstbuf);
  int32_t send_xmp_statfs(const std::string& tpath, const thrift_statvfs& tstbuf);
  void recv_xmp_statfs(thrift_statfs_reply& _return, const int32_t seqid);
  void xmp_open(thrift_open_reply& _return, const std::string& tpath, const thrift_fuse_file_info& tfi);
  int32_t send_xmp_open(const std::string& tpath, const thrift_fuse_file_info& tfi);
  void recv_xmp_open(thrift_open_reply& _return, const int32_t seqid);
  int32_t xmp_access(const std::string& tpath, const int32_t mask);
  int32_t send_xmp_access(const std::string& tpath, const int32_t mask);
  int32_t recv_xmp_access(const int32_t seqid);
  int32_t xmp_mknod(const std::string& tpath, const int32_t mode, const int64_t rdev);
  int32_t send_xmp_mknod(const std::string& tpath, const int32_t mode, const int64_t rdev);
  int32_t recv_xmp_mknod(const int32_t seqid);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  ::apache::thrift::async::TConcurrentClientSyncInfo sync_;
};

#ifdef _WIN32
  #pragma warning( pop )
#endif



#endif
