/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef NfsRpc_CONSTANTS_H
#define NfsRpc_CONSTANTS_H

#include "NfsRpc_types.h"



class NfsRpcConstants {
 public:
  NfsRpcConstants();

};

extern const NfsRpcConstants g_NfsRpc_constants;



#endif
