/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "NfsRpc_constants.h"



const NfsRpcConstants g_NfsRpc_constants;

NfsRpcConstants::NfsRpcConstants() {
}



