// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "gen-cpp/NfsRpc.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

#include <iostream>
using namespace std;

class NfsRpcHandler : virtual public NfsRpcIf {
 public:
  NfsRpcHandler() {
    // Your initialization goes here
  }

  int32_t xmp_open(const std::string& path, const thrift_fuse_file_info& fi) {
    // Your implementation goes here
    printf("xmp_open\n");
      return 0;
  }

  int32_t xmp_access(const std::string& path, const int32_t mask) {
    // Your implementation goes here
    printf("xmp_access\n");
      return 0;
  }

  int32_t xmp_mknod(const std::string& path, const int32_t mode, const int64_t rdev) {
    // Your implementation goes here
    printf("xmp_mknod\n");
      return 0;
  }

  int32_t xmp_remove(const std::string& path) {
    // Your implementation goes here
    printf("xmp_remove\n");
    return 0;
  }

  int32_t xmp_getattr(const std::string& path, const thrift_stat& stbuf) {
    // Your implementation goes here
    printf("xmp_getattr\n");
      return 0;
  }

  int32_t xmp_setattr(const std::string& path, const thrift_stat& stbuf) {
    // Your implementation goes here
    printf("xmp_setattr\n");
      return 0;
  }

  int32_t xmp_read(const std::string& path, const std::string& buf, const int64_t size, const int64_t offset, const thrift_fuse_file_info& fi) {
    // Your implementation goes here
    printf("xmp_read\n");
      return 0;
  }

  int32_t xmp_write(const std::string& path, const std::string& buf, const int64_t size, const int64_t offset, const thrift_fuse_file_info& fi) {
    // Your implementation goes here
    printf("xmp_write\n");
      return 0;
  }

  int32_t xmp_rename(const std::string& fromName, const std::string& to) {
    // Your implementation goes here
    printf("xmp_rename\n");
      return 0;
  }

  int32_t xmp_mkdir(const std::string& path, const int32_t mode) {
    // Your implementation goes here
    printf("xmp_mkdir\n");
      return 0;
  }

  int32_t xmp_rmdir(const std::string& path) {
    // Your implementation goes here
    printf("xmp_rmdir\n");
      return 0;
  }

  int32_t xmp_statfs(const std::string& path, const thrift_statvfs& stbuf) {
    // Your implementation goes here
    printf("xmp_statfs\n");
      return 0;
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<NfsRpcHandler> handler(new NfsRpcHandler());
  shared_ptr<TProcessor> processor(new NfsRpcProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);

    cout << "Starting Thrift Server" << endl;

  server.serve();
  return 0;
}

